# Generated by Django 5.0 on 2023-12-09 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='focususer',
            name='bio',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='focususer',
            name='followers',
            field=models.ManyToManyField(related_name='following', to='focus_user.focususer'),
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('caption', models.CharField(max_length=1000)),
                ('category', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images/')),
                ('average_rating', models.FloatField()),
                ('total_ratings', models.IntegerField()),
                ('upload_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='focus_user.focususer')),
            ],
        ),
    ]
