# Generated by Django 5.0 on 2023-12-13 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus_user', '0004_alter_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='raters',
            field=models.ManyToManyField(related_name='rated_uploads', to='focus_user.focususer'),
        ),
    ]
